# Generated by Django 5.0.1 on 2024-01-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('wp', 'Waiting for payment'), ('pd', 'Paid')], default='wp', max_length=2, null=True),
        ),
    ]
